server:
  port: 8002
spring:
  application:
    name: BIGOU-PRODUCT
  datasource:  #数据库的配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bigou_product?useUnicode=true&characterEncoding=UTF-8  #防止中文乱码
    username: admin
    password: admin
mybatis-plus:
  mapper-locations: classpath:cn/itsource/bigou/mapper/*Mapper.xml #扫mapper映射
  type-aliases-package: cn.itsource.bigou.domain,cn.itsource.bigou.query  #别名的配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true