server:
  port: 8003
  max-http-header-size: 4048576 #异常解决
spring:
  application:
    name: COMMON-PRIVODER
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/